pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/hitesh-ripplehire/interview-scheduler-backend.git'
            }
        }
        stage('Build Backend') {
            steps {
                sh '''
                # Install dependencies
                mvn clean install
                '''
            }
        }
        stage('Run Backend') {
            steps {
                sh '''
                # Start the server
                java -jar target/*.jar &
                '''
            }
        }
    }
}
